name: "Dash OS Pro Dashboard"
version: 0.0.8
slug: "dash_os_pro_dashboard"
description: "Long description"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl